version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.1

jobs:
  #configure a job called build-and-push to publish docker image to the docker hub registry only when the test job passed.
  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Building Docker image..."
          docker build -t $DOCKERHUB_USERNAME/education-space .
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $DOCKERHUB_USERNAME/education-space
  #build:
  #  docker:
  #    - image: cimg/node:16.10
  #  steps:
  #    - checkout
  #    - node/install-packages:
  #        pkg-manager: npm
  #    - run: |
  #        echo "Installing dependencies..."
  #        npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: main
