version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: DOCKERHUB_PASSWORD # DOCKER_PASSWORD is the default value
      - docker/build:
          image: $DOCKER_USERNAME/education-space
      - docker/push:
          image: $DOCKER_USERNAME/education-space

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a $HEROKU_APP_NAME
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
# Run only the build and test jobs when main branch is updated.
# Run all the jobs (including publish and deploy jobs) when release branch is updated
workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - release/v1.0.0
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release/v1.0.0
      - publish:
          requires:
            - test
          filters:
            branches:
              only: release/v1.0.0
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only: release/v1.0.0
